In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용한 1차원 배열로 변경하기 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
# 배열의 크기 확인
arr1.shape # 5개의 행이 쭈욱 있다. 의미


(5,)

In [6]:
# 2차원 List
data2 = [
         [1,2,3,4],
         [5,6,7,8]
         ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2 #2행4열

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape #2행4열 그러면 4차원 데이터이다.

(2, 4)

In [11]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros([3,5,2]) # [page,행,열]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# 숫자 8로 구성된 3행 5열배열 생성
np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [20]:
# 범위가 있는배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1.dtype

dtype('float64')

In [23]:
arr3 = np.array([1,2,3,4,5],dtype =np.int64)
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [24]:
# data type을 변경
float_arr1 =arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [25]:
float_arr1

array([1., 2., 3., 4., 5.])

In [27]:
# 연산
arr1 = np.array([
                [1,2,3],
                [4,5,6],
                ], dtype=np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr2 = np.array([
                [7,8,9],
                [10,11,12],
                ], dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
# 끼리끼리 한다.

In [33]:
arr1 + arr3

array([[2.        , 2.5       , 3.33333333],
       [4.25      , 5.2       , 6.16666667]])

In [34]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [35]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [36]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [37]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

5

In [46]:
arr[5:9]

array([5, 6, 7, 8])

In [47]:
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[8:]

array([12,  9])

In [50]:
### 2차원 배열

In [53]:
arr2d = np.array([
         [1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]
         ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
arr2d.dtype

dtype('int64')

In [58]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [65]:
# 1에서 2번행의 자료 출력
arr2d[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [67]:
# 0, 1열의 자료 출력
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [68]:
# 1행2열의 자료 출력
arr2d[1,2]

7

In [69]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
arr2d[:2,1:3]  = 0

In [75]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준평균 정규 분포
- randint : 균일 분포의 정수 난수

### Boolean Indexing

In [135]:
names = np.array(["Charles","Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7, 4)

In [136]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [137]:
names.shape

(7,)

In [138]:
data

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [ 1.41515595,  0.04287405,  1.1596631 , -1.93389439],
       [ 1.87001566,  1.85249888,  1.60374417, -1.41408087],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117],
       [-2.03123759, -0.88588887,  0.83367066,  1.33765047],
       [ 0.15972634,  0.15104231, -0.80210484,  0.91296747],
       [-1.1876303 ,  0.080729  ,  0.09683049,  0.32331509]])

In [139]:
data.shape

(7, 4)

In [140]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [141]:
data[names == "Charles", :]

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117]])

In [142]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [ 1.41515595,  0.04287405,  1.1596631 , -1.93389439],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117],
       [ 0.15972634,  0.15104231, -0.80210484,  0.91296747],
       [-1.1876303 ,  0.080729  ,  0.09683049,  0.32331509]])

In [143]:
data[:]

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [ 1.41515595,  0.04287405,  1.1596631 , -1.93389439],
       [ 1.87001566,  1.85249888,  1.60374417, -1.41408087],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117],
       [-2.03123759, -0.88588887,  0.83367066,  1.33765047],
       [ 0.15972634,  0.15104231, -0.80210484,  0.91296747],
       [-1.1876303 ,  0.080729  ,  0.09683049,  0.32331509]])

In [144]:
data[:,3]

array([ 0.19480192, -1.93389439, -1.41408087, -1.16501117,  1.33765047,
        0.91296747,  0.32331509])

In [145]:
# data의 4번째 열 값중 0보다 작은 것의 mask만들기

data[data[:, 3]<0, :]

array([[ 1.41515595,  0.04287405,  1.1596631 , -1.93389439],
       [ 1.87001566,  1.85249888,  1.60374417, -1.41408087],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117]])

In [146]:
data[:]

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [ 1.41515595,  0.04287405,  1.1596631 , -1.93389439],
       [ 1.87001566,  1.85249888,  1.60374417, -1.41408087],
       [-1.95739821, -0.10717678,  0.32913984, -1.16501117],
       [-2.03123759, -0.88588887,  0.83367066,  1.33765047],
       [ 0.15972634,  0.15104231, -0.80210484,  0.91296747],
       [-1.1876303 ,  0.080729  ,  0.09683049,  0.32331509]])

In [147]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:, 3] < 0, :] = 0
data

array([[ 0.69889138, -0.28622204, -0.39884863,  0.19480192],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-2.03123759, -0.88588887,  0.83367066,  1.33765047],
       [ 0.15972634,  0.15104231, -0.80210484,  0.91296747],
       [-1.1876303 ,  0.080729  ,  0.09683049,  0.32331509]])

In [148]:
# 정렬
arr = np.random.rand(8)
arr

array([0.85426923, 0.45539142, 0.94770563, 0.90006404, 0.888672  ,
       0.19060769, 0.18157849, 0.37813732])

In [149]:
# 오름차순 정렬
np.sort(arr)

array([0.18157849, 0.19060769, 0.37813732, 0.45539142, 0.85426923,
       0.888672  , 0.90006404, 0.94770563])

In [150]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.94770563, 0.90006404, 0.888672  , 0.85426923, 0.45539142,
       0.37813732, 0.19060769, 0.18157849])

In [151]:
arr = np.random.rand(5,3)
arr

array([[0.42238245, 0.79998872, 0.46642292],
       [0.13919564, 0.89590463, 0.54431828],
       [0.64308117, 0.88134066, 0.11015875],
       [0.83275822, 0.43747489, 0.11182124],
       [0.85722315, 0.92605765, 0.5056908 ]])

In [152]:
np.sort(arr, axis=0) #0 : 열방향

array([[0.13919564, 0.43747489, 0.11015875],
       [0.42238245, 0.79998872, 0.11182124],
       [0.64308117, 0.88134066, 0.46642292],
       [0.83275822, 0.89590463, 0.5056908 ],
       [0.85722315, 0.92605765, 0.54431828]])

In [153]:
np.sort(arr, axis=1) #0 : 행방향

array([[0.42238245, 0.46642292, 0.79998872],
       [0.13919564, 0.54431828, 0.89590463],
       [0.11015875, 0.64308117, 0.88134066],
       [0.11182124, 0.43747489, 0.83275822],
       [0.5056908 , 0.85722315, 0.92605765]])

In [155]:
np.sort(arr, axis=1)[:,::-1]

array([[0.79998872, 0.46642292, 0.42238245],
       [0.89590463, 0.54431828, 0.13919564],
       [0.88134066, 0.64308117, 0.11015875],
       [0.83275822, 0.43747489, 0.11182124],
       [0.92605765, 0.85722315, 0.5056908 ]])

In [156]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape 엄청!!!!!!중요!!!!!!

In [170]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
arr.shape

(8,)

In [172]:
# 2차원 배열로 변경
arr1 = np.reshape(arr,[2,4])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [173]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, [2,2,2]) #(page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [174]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1,1) # 데이터 갯수를 정할 수 없을때 -1, 차원수 표시 1
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [175]:
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [176]:
arr3 == arr4
# 달라도 기본적 베이스가 같은 값이기에 문제없다.

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])