# 서울시 CCTV 현황 분석 및 인구 현황 분석

### CCTV설치 현황

In [82]:
import pandas as pd

In [83]:
CCTV_Seoul = pd.read_excel("../Data/CCTV_in_Seoul_2018.xlsx")
CCTV_Seoul.head()

기관명    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671

In [84]:
CCTV_Seoul.tail()

기관명    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
20  용산구  2063    1279.0  152.0  201.0    107    102     89     60     73
21  은평구  2962    1365.0   83.0   99.0    343    180    296    229    367
22  종로구  1471       8.0    7.0  599.0    132    195    148    281    101
23   중구  1544      25.0  165.0  114.0     80    245    270    317    328
24  중랑구  1068       NaN    NaN    NaN    770    102    121     66      9

In [85]:
CCTV_Seoul.columns

Index(['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', '2016년',
       '2017년', '2018년'],
      dtype='object')

In [86]:
# CCTV_Seoul의 첫번째 컬럼 확인
CCTV_Seoul.columns[0]

'기관명'

In [87]:
# 기관명 -> 구별로 변경
CCTV_Seoul.rename(columns={'기관명': '구별'}, inplace=True)
CCTV_Seoul.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671

In [88]:
# NaN을 확인하고 NaN을 0으로 대체하기
CCTV_Seoul=CCTV_Seoul.fillna(0)
CCTV_Seoul.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671

In [89]:
CCTV_Seoul.tail()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
20  용산구  2063    1279.0  152.0  201.0    107    102     89     60     73
21  은평구  2962    1365.0   83.0   99.0    343    180    296    229    367
22  종로구  1471       8.0    7.0  599.0    132    195    148    281    101
23   중구  1544      25.0  165.0  114.0     80    245    270    317    328
24  중랑구  1068       0.0    0.0    0.0    770    102    121     66      9

---
### 인구현황

In [90]:
pop_Seoul = pd.read_excel("../Data/population_in_Seoul_2020.xlsx")
pop_Seoul

report Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         기간        자치구         세대         인구         인구         인구   
1         기간        자치구         세대         합계         합계         합계   
2         기간        자치구         세대          계         남자         여자   
3   2020.1/4         합계    4354006   10013781    4874995    5138786   
4   2020.1/4        종로구      74151     161984      78271      83713   
5   2020.1/4         중구      63045     136469      66769      69700   
6   2020.1/4        용산구     110895     246165     119961     126204   
7   2020.1/4        성동구     135643     307193     149891     157302   
8   2020.1/4        광진구     165287     365990     176226     189764   
9   2020.1/4       동대문구     165279     362793     178202     184591   
10  2020.1/4        중랑구     182220     400678     198122     202556   
11  2020.1/4        성북구     193801     454532     218561     235971   
12  2020.1/4        강북구     144805     316750     154141     162609   
13  2020.1/4        도봉구     138595     333495     162774     170721   
14  2020.1/4        노원구     217148     535495     258696     276799   
15  2020.1/4        은평구     208209     482509     231953     250556   
16  2020.1/4       서대문구     142109     325875     154502     171373   
17  2020.1/4        마포구     176133     386086     181204     204882   
18  2020.1/4        양천구     177436     460532     226109     234423   
19  2020.1/4        강서구     263645     595703     288134     307569   
20  2020.1/4        구로구     177275     438308     218970     219338   
21  2020.1/4        금천구     111542     251370     128643     122727   
22  2020.1/4       영등포구     177743     404766     202617     202149   
23  2020.1/4        동작구     181761     407802     196943     210859   
24  2020.1/4        관악구     270760     516662     258982     257680   
25  2020.1/4        서초구     173580     434801     207877     226924   
26  2020.1/4        강남구     233624     549898     263163     286735   
27  2020.1/4        송파구     279301     680883     329058     351825   
28  2020.1/4        강동구     190019     457042     225226     231816   

   Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0          인구         인구         인구         인구          인구          인구   
1         한국인        한국인        한국인      등록외국인       등록외국인       등록외국인   
2           계         남자         여자          계          남자          여자   
3     9733655    4742217    4991438     280126      132778      147348   
4      151217      73704      77513      10767        4567        6200   
5      126175      61839      64336      10294        4930        5364   
6      229579     110667     118912      16586        9294        7292   
7      299042     146300     152742       8151        3591        4560   
8      350417     169568     180849      15573        6658        8915   
9      346156     171896     174260      16637        6306       10331   
10     395619     196076     199543       5059        2046        3013   
11     442494     213926     228568      12038        4635        7403   
12     312985     152747     160238       3765        1394        2371   
13     331238     161879     169359       2257         895        1362   
14     531037     256726     274311       4458        1970        2488   
15     478019     230147     247872       4490        1806        2684   
16     312642     150051     162591      13233        4451        8782   
17     374570     176943     197627      11516        4261        7255   
18     456339     224241     232098       4193        1868        2325   
19     589302     285085     304217       6401        3049        3352   
20     405837     200558     205279      32471       18412       14059   
21     232583     118044     114539      18787       10599        8188   
22     371903     184316     187587      32863       18301       14562   
23     395014     191272     203742      12788        5671        7117   
24     499374     250743 

In [91]:
pop_Seoul.columns

Index(['report', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [92]:
# 엑셀에서 원하는 값만 가져오기
pop_Seoul = pd.read_excel("../Data/population_in_Seoul_2020.xlsx",
                          header=3,
                          usecols="B,D,G,J,N"  # 엑셀의 컬럼 번호로

                        )
pop_Seoul

자치구         계      계.1     계.2  65세이상고령자
0     합계  10013781  9733655  280126   1518239
1    종로구    161984   151217   10767     28073
2     중구    136469   126175   10294     23794
3    용산구    246165   229579   16586     39439
4    성동구    307193   299042    8151     44728
5    광진구    365990   350417   15573     48989
6   동대문구    362793   346156   16637     60367
7    중랑구    400678   395619    5059     66764
8    성북구    454532   442494   12038     72172
9    강북구    316750   312985    3765     61660
10   도봉구    333495   331238    2257     60023
11   노원구    535495   531037    4458     82682
12   은평구    482509   478019    4490     82245
13  서대문구    325875   312642   13233     53038
14   마포구    386086   374570   11516     53283
15   양천구    460532   456339    4193     62761
16   강서구    595703   589302    6401     85992
17   구로구    438308   405837   32471     67432
18   금천구    251370   232583   18787     38508
19  영등포구    404766   371903   32863     59373
20   동작구    407802   395014   12788     63378
21   관악구    516662   499374   17288     76664
22   서초구    434801   430568    4233     58332
23   강남구    549898   544804    5094     72602
24   송파구    680883   674095    6788     89539
25   강동구    457042   452646    4396     66401

In [93]:
pop_Seoul.columns = ['구별','인구수','한국인','외국인','고령자']
pop_Seoul.head()

구별       인구수      한국인     외국인      고령자
0   합계  10013781  9733655  280126  1518239
1  종로구    161984   151217   10767    28073
2   중구    136469   126175   10294    23794
3  용산구    246165   229579   16586    39439
4  성동구    307193   299042    8151    44728

In [94]:
# 합계 행을 삭제
pop_Seoul.drop(0, inplace=True)
pop_Seoul.head()

구별     인구수     한국인    외국인    고령자
1  종로구  161984  151217  10767  28073
2   중구  136469  126175  10294  23794
3  용산구  246165  229579  16586  39439
4  성동구  307193  299042   8151  44728
5  광진구  365990  350417  15573  48989

In [95]:
pop_Seoul.tail()

구별     인구수     한국인    외국인    고령자
21  관악구  516662  499374  17288  76664
22  서초구  434801  430568   4233  58332
23  강남구  549898  544804   5094  72602
24  송파구  680883  674095   6788  89539
25  강동구  457042  452646   4396  66401

### CCTV 현황

In [96]:
# CCTV에서 소계로 오름차순 정렬
CCTV_Seoul.sort_values(by='소계', ascending=True).head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
9   도봉구   858     197.0   66.0    8.0    185     59    155    117     71
24  중랑구  1068       0.0    0.0    0.0    770    102    121     66      9
2   강북구  1265     243.0   88.0  141.0     74    145    254      1    319
22  종로구  1471       8.0    7.0  599.0    132    195    148    281    101
23   중구  1544      25.0  165.0  114.0     80    245    270    317    328

> CCTV 댓수가 적은 지역으로는 도봉구,중랑구, 강북구, 종로구, 중구 순이다.ㅡ

In [97]:
# CCTV에서 소계로 내림차순 정렬
CCTV_Seoul.sort_values(by='소계', ascending=False).head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0   강남구  5221    1944.0  195.0  316.0    430    546    765    577    448
4   관악구  3985     430.0   56.0  419.0    487    609    619    694    671
6   구로구  3227     852.0  219.0  349.0    187    268    326    540    486
16  성북구  3003     779.0   84.0  304.0    241    279    388    285    643
21  은평구  2962    1365.0   83.0   99.0    343    180    296    229    367

> CCTV 댓수가 많은 지역으로는 강남구, 관악구, 구로구, 성북구, 은평구 순이다.

---
#### 최근 3년간 CCTV증가율 구해서 CCTV가 제일 많이 증가한 구를 검색후 정렬


In [102]:
a1 = CCTV_Seoul.iloc[:,2:7].sum(axis=1)
a2 = CCTV_Seoul.iloc[:,7:10].sum(axis=1)

In [103]:
CCTV_Seoul['최근증가율'] =  (a2 / a1) * 100

In [104]:
CCTV_Seoul.sort_values(by='최근증가율', ascending=False).head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년  \
23    중구  1544      25.0  165.0  114.0     80    245    270    317    328   
19  영등포구  2495     132.0  121.0  206.0    217    366    289    371    793   
15   성동구  2679     665.0  109.0  118.0    101    258    201    933    294   
7    금천구  1634      27.0   17.0  242.0    101    382    136    199    530   
5    광진구  1581     470.0   42.0   83.0     87     64     21    468    346   

         최근증가율  
23  145.468998  
19  139.443378  
15  114.148681  
7   112.483745  
5   111.930295

> 결과를 보면 최근 3년간의 CCTV가 2015년 이전에 비해 가장 많이 증가한 곳은 중구, 영등포구, 성동구, 금천구, 광진구 순이다.

--- 
### 인구현황

In [105]:
# 구별 Data의 유효성 확인
len(pop_Seoul['구별'].unique())

25

In [106]:
pop_Seoul.head()

구별     인구수     한국인    외국인    고령자
1  종로구  161984  151217  10767  28073
2   중구  136469  126175  10294  23794
3  용산구  246165  229579  16586  39439
4  성동구  307193  299042   8151  44728
5  광진구  365990  350417  15573  48989

In [116]:
pop_Seoul['외국인비율']=pop_Seoul['외국인']/pop_Seoul['인구수']*100
pop_Seoul['고령자비율']=pop_Seoul['고령자']/pop_Seoul['인구수']*100
pop_Seoul.head()

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
1  종로구  161984  151217  10767  28073  6.646953  17.330724
2   중구  136469  126175  10294  23794  7.543105  17.435462
3  용산구  246165  229579  16586  39439  6.737757  16.021368
4  성동구  307193  299042   8151  44728  2.653381  14.560228
5  광진구  365990  350417  15573  48989  4.255034  13.385338

In [119]:
# 인구수가 제일 많은 지역은 Top5
pop_Seoul.sort_values(by='인구수', ascending=False).head(5)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24  송파구  680883  674095   6788  89539  0.996941  13.150424
16  강서구  595703  589302   6401  85992  1.074529  14.435381
23  강남구  549898  544804   5094  72602  0.926354  13.202812
11  노원구  535495  531037   4458  82682  0.832501  15.440294
21  관악구  516662  499374  17288  76664  3.346095  14.838328

In [120]:
# 외국인이 제일 많은 지역은 Top5
pop_Seoul.sort_values(by='외국인', ascending=False).head(5)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
17   구로구  438308  405837  32471  67432  7.408261  15.384615
18   금천구  251370  232583  18787  38508  7.473843  15.319251
21   관악구  516662  499374  17288  76664  3.346095  14.838328
6   동대문구  362793  346156  16637  60367  4.585811  16.639516

In [121]:
# 외국인 비율이 높은 지역은 Top5
pop_Seoul.sort_values(by='외국인비율', ascending=False).head(5)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
19  영등포구  404766  371903  32863  59373  8.119012  14.668475
2     중구  136469  126175  10294  23794  7.543105  17.435462
18   금천구  251370  232583  18787  38508  7.473843  15.319251
17   구로구  438308  405837  32471  67432  7.408261  15.384615
3    용산구  246165  229579  16586  39439  6.737757  16.021368

In [122]:
# 고령자 정렬
pop_Seoul.sort_values(by='고령자', ascending=False).head(5)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
24  송파구  680883  674095   6788  89539  0.996941  13.150424
16  강서구  595703  589302   6401  85992  1.074529  14.435381
11  노원구  535495  531037   4458  82682  0.832501  15.440294
12  은평구  482509  478019   4490  82245  0.930553  17.045278
21  관악구  516662  499374  17288  76664  3.346095  14.838328

In [123]:
# 고령자 비율 정렬
pop_Seoul.sort_values(by='고령자비율', ascending=False).head(5)

구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
9   강북구  316750  312985   3765  61660  1.188635  19.466456
10  도봉구  333495  331238   2257  60023  0.676772  17.998171
2    중구  136469  126175  10294  23794  7.543105  17.435462
1   종로구  161984  151217  10767  28073  6.646953  17.330724
12  은평구  482509  478019   4490  82245  0.930553  17.045278

--- 
# CCTV와 인구현황 합치기

In [147]:
Data_result = pd.merge(CCTV_Seoul, pop_Seoul, on= '구별')
Data_result.head()

구별    소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년  \
0  강남구  5221    1944.0  195.0  316.0    430    546    765    577    448   
1  강동구  1879     303.0  387.0  134.0     59    144    194    273    385   
2  강북구  1265     243.0   88.0  141.0     74    145    254      1    319   
3  강서구  1617     219.0  155.0  118.0    230    187    190    264    254   
4  관악구  3985     430.0   56.0  419.0    487    609    619    694    671   

       최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율  
0  52.171379  549898  544804   5094  72602  0.926354  13.202812  
1  82.960078  457042  452646   4396  66401  0.961837  14.528424  
2  83.068017  316750  312985   3765  61660  1.188635  19.466456  
3  77.887789  595703  589302   6401  85992  1.074529  14.435381  
4  99.150425  516662  499374  17288  76664  3.346095  14.838328

In [148]:
Data_result.set_index('구별', inplace=True)
Data_result.head()

소계  2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년  \
구별                                                                     
강남구  5221    1944.0  195.0  316.0    430    546    765    577    448   
강동구  1879     303.0  387.0  134.0     59    144    194    273    385   
강북구  1265     243.0   88.0  141.0     74    145    254      1    319   
강서구  1617     219.0  155.0  118.0    230    187    190    264    254   
관악구  3985     430.0   56.0  419.0    487    609    619    694    671   

         최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율  
구별                                                                 
강남구  52.171379  549898  544804   5094  72602  0.926354  13.202812  
강동구  82.960078  457042  452646   4396  66401  0.961837  14.528424  
강북구  83.068017  316750  312985   3765  61660  1.188635  19.466456  
강서구  77.887789  595703  589302   6401  85992  1.074529  14.435381  
관악구  99.150425  516662  499374  17288  76664  3.346095  14.838328

In [155]:
# 구별을 index로 만들기
delColumn = Data_result.columns[2:9]

for i in delColumn:
    del Data_result[i]
Data_result.head()

소계  2011년 이전
구별                 
강남구  5221    1944.0
강동구  1879     303.0
강북구  1265     243.0
강서구  1617     219.0
관악구  3985     430.0

In [136]:
import numpy as np

In [150]:
# 고령자 비율과 소계의 상관계수
np.corrcoef(Data_result['고령자비율'], Data_result['소계']) 
# 결과 : 역상관관계가 나온다.

array([[ 1.        , -0.44225083],
       [-0.44225083,  1.        ]])

In [151]:
# 고령자와 소계의 상관계수
np.corrcoef(Data_result['고령자'], Data_result['소계'])
# 결과 : 상관이 없다.

array([[1.        , 0.28638538],
       [0.28638538, 1.        ]])

In [152]:
# 외국인 비율과 소계의 상관계수 
np.corrcoef(Data_result['외국인비율'], Data_result['소계'])
# 결과 :상관이 없다.

array([[ 1.        , -0.06215538],
       [-0.06215538,  1.        ]])

In [153]:
# 외국인과 소계의 상관계수
np.corrcoef(Data_result['외국인'], Data_result['소계'])
# 결과 : 상관없다.

array([[1.        , 0.17444235],
       [0.17444235, 1.        ]])

In [154]:
# 인구수와 소계의 상관계수
np.corrcoef(Data_result['인구수'], Data_result['소계'])
# 결과 : 양의 상관이 있다.

array([[1.        , 0.38064812],
       [0.38064812, 1.        ]])

> 고령자 비율의 상관계수를 보면 역상관이 발생하고 이는고령자가 아닌젊은 층 비율이 높은 곳에 CCTV가 많이 설치되는 경행을 보이며
> 주로 인구수와 양의 상관을 보이고 있어 CCTV 댓수는 인구수에 비례하여 증가하는 경향을 보인다.