In [31]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격 여부   
gre : 영어성적    
gpa : 학점    
rank : 지원한 대학원 수준   

## Preprocessig (전처리)

In [32]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [33]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결축치 데이터를 다른값으로 대체
# data.fillna(100)

In [34]:
# 결측치 처리 확인
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [35]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [36]:
# 영어 점수의 최소값과 최대값
print('최대값:', data['gre'].max())
print('최소값:', data['gre'].min())

최대값: 800.0
최소값: 220.0


In [37]:
#  Training Data
x = data[['gre','gpa','rank']]
# x와 같이 입력층 3개 만들었다.
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [38]:
# traget Data
y = data['admit']
# y와 같이 출력층은 1개이다.
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [39]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

---
## Deep Learning Model 만들기

In [40]:
from tensorflow import keras

In [41]:
input_layer =keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation='tanh')
output_layer = keras.layers.Dense(1, activation='sigmoid')


In [42]:
model = keras.Sequential(
    [
        input_layer,
        hidden_layer,
        output_layer
    ]
)


In [43]:
# 손실함수
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy') 
# optimizer= 정답값(y) - 에측값(y^)
# optimizer : learning rate를 알맞게 조정해줌
# - adam
# - adagrad
# - asadelta
# - rmsprop
# - sgd
# - less : 손실함수
# - binary_crossentropy : 분류 및 혹률 예측
# - metrics : 모델의 평가 기준

In [44]:
# 학습 시키기
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
14/14 [==============================] - 1s 2ms/step - loss: 0.7134 - accuracy: 0.5247
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6792 - accuracy: 0.5835
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6715 - accuracy: 0.5976
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6681 - accuracy: 0.5953
Epoch 5/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.5294
Epoch 6/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6795 - accuracy: 0.5741
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6678 - accuracy: 0.6212
Epoch 8/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6752 - accuracy: 0.5647
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6589 - accuracy: 0.6329
Epoch 10/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6567 - accuracy: 0.6141
Epoch 11/

In [45]:
# hiddent layer의 가중치 값 출력
hidden_layer.get_weights()[0]
# 0.08779569,  0.11321339, -0.1506861 ,  0.14944696, -0.05578093, +b 이렇게 크기만 커진다

array([[-6.62251934e-02,  8.64836425e-02, -7.25331381e-02,
         1.36434555e-01, -2.64285691e-03,  1.24467164e-01,
         1.07320845e-01,  3.49981673e-02, -4.72781956e-02,
        -8.82367268e-02,  8.28878433e-02,  2.41571874e-03,
        -3.37426104e-02,  6.43826276e-02, -4.63781059e-02,
         6.90940320e-02, -6.23623505e-02, -1.30554512e-01,
         1.16113096e-01, -1.08003914e-01, -1.30783781e-01,
        -5.62833771e-02, -6.62401840e-02, -9.05193314e-02,
        -2.47876514e-02,  3.81390303e-02, -7.57083222e-02,
        -1.35052219e-01, -1.40965924e-01,  1.77006051e-02,
        -3.41699682e-02,  4.55437601e-02, -1.47610232e-01,
        -4.59648222e-02,  1.03303254e-01,  1.37131810e-01,
        -1.38551667e-01,  5.35351187e-02,  7.25643784e-02,
         1.27142102e-01,  1.41481608e-01, -1.61776766e-02,
         3.26345116e-03,  1.32528663e-01, -5.24231791e-02,
        -6.49454147e-02, -1.39705926e-01,  1.30633533e-01,
        -1.01228282e-01, -1.42375650e-02,  1.10136956e-0

In [46]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [47]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       ...,
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.]], dtype=float32)>